name: Secrets Scan
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:

  timeout-minutes: 10
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '27 4 * * 1'
permissions:
  contents: read
jobs:
  trufflehog:
    name: TruffleHog
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4
        with:
          fetch-depth: 0
      - uses: trufflesecurity/trufflehog@ac0805e53b065e7188181fc80dce1800dfa51ab9  # was: @main
        with:
          path: ./
          extra_args: --only-verified
