name: SurrealDB Integration (Ubuntu)

permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  surreal-ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      - run: cargo test --workspace
        env:
          RUST_LOG: debug
      - name: SurrealDB Mem/RocksDB test
        run: |
          cargo test -p surreal-bridge -- --nocapture
        env:
          RUST_LOG: debug
        continue-on-error: true
